---
- name: command vs shell difference
  hosts: nodes
  #gather_facts: no
  tasks:
    - name: check up time
      ansible.builtin.command: uptime
      register: command_output
    - name: command output
      ansible.builtin.debug:
        msg: command_output.stdout_lines

