---
- name: shell module example
  hosts: nodes
  gather_facts: no
  tasks:
    - name: list files and folders
      ansible.builtin.shell: 'ls -l *'
      register: command_output
    - name: print command output
      ansible.builtin.debug:
        msg: command_output.stdout_lines


